language: ruby
cache: bundler
bundler_args: "--binstubs --path ../bundle --retry=3 --jobs=3"
before_install:
  - gem install bundler
  - rvm get head
  - bundle install
script:
  - bin/test
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
env:
  - "RAILS_VERSION=6.0.2"
  - "RAILS_VERSION=5.2.4"
